-- EUPHORIA AUCTION: Supabase schema + secure auction RPCs
create extension if not exists pgcrypto;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text unique not null,
  color_key text not null,
  sort_order int not null
);

create table if not exists public.pools (
  id uuid primary key default gen_random_uuid(),
  batch_year int not null check (batch_year between 2021 and 2025),
  gender text not null check (gender in ('Male','Female')),
  unique(batch_year, gender)
);

create table if not exists public.team_pool_balances (
  id bigint generated by default as identity primary key,
  pool_id uuid not null references public.pools(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  starting_ep int not null default 150 check (starting_ep >= 0),
  remaining_ep int not null default 150 check (remaining_ep >= 0),
  unique(pool_id, team_id)
);

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  pool_id uuid not null references public.pools(id) on delete cascade,
  roll_number text not null,
  name text not null,
  base_price int not null default 3 check (base_price = 3),
  status text not null default 'available' check (status in ('available','live','sold','unsold')),
  sold_team_id uuid references public.teams(id),
  sold_price int,
  created_at timestamptz not null default now()
);

create table if not exists public.auction_states (
  pool_id uuid primary key references public.pools(id) on delete cascade,
  current_player_id uuid references public.players(id),
  current_bid int not null default 3,
  leader_team_id uuid references public.teams(id),
  status text not null default 'idle' check (status in ('idle','live','sold','unsold')),
  updated_at timestamptz not null default now()
);

create table if not exists public.bids (
  id bigint generated by default as identity primary key,
  pool_id uuid not null references public.pools(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  amount int not null check (amount >= 3),
  created_at timestamptz not null default now()
);

create table if not exists public.auction_results (
  id bigint generated by default as identity primary key,
  pool_id uuid not null references public.pools(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  team_id uuid references public.teams(id),
  final_price int not null default 0,
  status text not null check (status in ('SOLD','UNSOLD')),
  created_at timestamptz not null default now()
);

insert into public.teams(name,color_key,sort_order) values
('Falcons','blue',1),('Eagles','yellow',2),('Thunderbirds','purple',3),('Griffins','red',4),('Phoenix','orange',5)
on conflict(name) do update set color_key=excluded.color_key, sort_order=excluded.sort_order;

insert into public.pools(batch_year,gender)
select y, g from generate_series(2021,2025) y cross join (values('Male'),('Female')) v(g)
on conflict(batch_year,gender) do nothing;

insert into public.team_pool_balances(pool_id,team_id)
select p.id,t.id from public.pools p cross join public.teams t
on conflict(pool_id,team_id) do nothing;

insert into public.auction_states(pool_id)
select p.id from public.pools p
on conflict(pool_id) do nothing;

alter table public.teams enable row level security;
alter table public.pools enable row level security;
alter table public.team_pool_balances enable row level security;
alter table public.players enable row level security;
alter table public.auction_states enable row level security;
alter table public.bids enable row level security;
alter table public.auction_results enable row level security;

drop policy if exists "public read teams" on public.teams;
create policy "public read teams" on public.teams for select using (true);
drop policy if exists "public read pools" on public.pools;
create policy "public read pools" on public.pools for select using (true);
drop policy if exists "public read balances" on public.team_pool_balances;
create policy "public read balances" on public.team_pool_balances for select using (true);
drop policy if exists "public read players" on public.players;
create policy "public read players" on public.players for select using (status <> 'unsold');
drop policy if exists "public read auction states" on public.auction_states;
create policy "public read auction states" on public.auction_states for select using (true);
drop policy if exists "public read bids" on public.bids;
create policy "public read bids" on public.bids for select using (true);
drop policy if exists "public read results" on public.auction_results;
create policy "public read results" on public.auction_results for select using (true);

-- Authenticated users are the admin group for this project.
-- Create only your admin accounts in Supabase Auth.
create or replace function public.next_bid_amount(b int) returns int
language sql immutable as $$ select case when b < 10 then b+1 when b < 20 then b+2 else b+5 end $$;

create or replace function public.start_player(p_pool_id uuid, p_roll_number text, p_name text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare pid uuid;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  insert into players(pool_id,roll_number,name,status) values(p_pool_id,p_roll_number,p_name,'live') returning id into pid;
  update auction_states set current_player_id=pid,current_bid=3,leader_team_id=null,status='live',updated_at=now() where pool_id=p_pool_id;
  return jsonb_build_object('player_id',pid);
end $$;

create or replace function public.place_bid(p_pool_id uuid, p_team_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s auction_states%rowtype; next_amount int; remaining int;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  select * into s from auction_states where pool_id=p_pool_id for update;
  if s.current_player_id is null or s.status <> 'live' then raise exception 'No live player'; end if;
  next_amount := public.next_bid_amount(s.current_bid);
  select remaining_ep into remaining from team_pool_balances where pool_id=p_pool_id and team_id=p_team_id for update;
  if remaining is null then raise exception 'Team is not configured for this pool'; end if;
  if remaining < next_amount then raise exception 'Team cannot afford % EP', next_amount; end if;
  if s.leader_team_id = p_team_id then raise exception 'That team already leads'; end if;
  insert into bids(pool_id,player_id,team_id,amount) values(p_pool_id,s.current_player_id,p_team_id,next_amount);
  update auction_states set current_bid=next_amount,leader_team_id=p_team_id,updated_at=now() where pool_id=p_pool_id;
  return jsonb_build_object('amount',next_amount);
end $$;

create or replace function public.sell_current_player(p_pool_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s auction_states%rowtype;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  select * into s from auction_states where pool_id=p_pool_id for update;
  if s.current_player_id is null or s.leader_team_id is null then raise exception 'Player has no winning team'; end if;
  update team_pool_balances set remaining_ep=remaining_ep-s.current_bid where pool_id=p_pool_id and team_id=s.leader_team_id and remaining_ep>=s.current_bid;
  if not found then raise exception 'Insufficient team balance'; end if;
  update players set status='sold',sold_team_id=s.leader_team_id,sold_price=s.current_bid where id=s.current_player_id;
  insert into auction_results(pool_id,player_id,team_id,final_price,status) values(p_pool_id,s.current_player_id,s.leader_team_id,s.current_bid,'SOLD');
  update auction_states set current_player_id=null,current_bid=3,leader_team_id=null,status='idle',updated_at=now() where pool_id=p_pool_id;
  return jsonb_build_object('sold',true);
end $$;

create or replace function public.mark_unsold(p_pool_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s auction_states%rowtype;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  select * into s from auction_states where pool_id=p_pool_id for update;
  if s.current_player_id is null then raise exception 'No live player'; end if;
  update players set status='unsold' where id=s.current_player_id;
  insert into auction_results(pool_id,player_id,final_price,status) values(p_pool_id,s.current_player_id,0,'UNSOLD');
  update auction_states set current_player_id=null,current_bid=3,leader_team_id=null,status='idle',updated_at=now() where pool_id=p_pool_id;
  return jsonb_build_object('unsold',true);
end $$;

create or replace function public.relist_player(p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p players%rowtype;
begin
  if auth.uid() is null then raise exception 'Admin login required'; end if;
  select * into p from players where id=p_player_id;
  if p.status <> 'unsold' then raise exception 'Only unsold players can be brought back'; end if;
  update players set status='available' where id=p_player_id;
  return jsonb_build_object('player_id',p_player_id,'base_price',3);
end $$;

-- Realtime
alter publication supabase_realtime add table public.auction_states;
alter publication supabase_realtime add table public.players;
alter publication supabase_realtime add table public.bids;
alter publication supabase_realtime add table public.team_pool_balances;
alter publication supabase_realtime add table public.auction_results;
